short_deck_rl/short_deck_rl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shortdeck.urls')),
]

short_deck_rl/shortdeck/urls.py
from django.urls import path
from . import views
from .views import start_game, end_game, hand_review, decision_data_view, hand_review_page, logout_view, get_pot, change_password

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('shortdeck/', views.shortdeck, name='shortdeck'),
    path('profile/manage/', views.manage_profile, name='manage_profile'),
    path('start_game/', start_game, name='start_game'),
    path('end_game/', end_game, name='end_game'),
    path('hand_review/', hand_review, name='hand_review'),
    path('decision-data/<int:action_id>/', decision_data_view, name='decision-data'),
    path('change_avatar/', views.change_avatar, name='change_avatar'),
    path('profile/change_avatar/', views.change_avatar, name='change_avatar'),
    path('hand_review_page/', views.hand_review_page, name='hand_review_page'),
    path('hand_review_page/<int:hand_id>/', views.hand_review_page, name='hand_review_detail'),
    path('logout/', views.logout_view, name='logout'),
    path('get_pot/', views.get_pot, name='get_pot'),
    path('change-password/', views.change_password, name='change_password'),
]

short_deck_rl/shortdeck/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum

# Define the avatar choices
AVATAR_CHOICES = (
    ('avatar1.webp', 'Dog'),
    ('avatar2.webp', 'cheetah'),
    ('avatar3.webp', 'Goat'),
    ('avatar4.webp', 'raccoon'),
    ('avatar5.webp', 'panda'),
    ('avatar6.webp', 'fox'),
    ('avatar7.webp', 'owl'),
    ('avatar8.webp', 'kitten'),
    ('avatar9.webp', 'monkey'),
    ('avatar10.webp', 'moose'),
)

#User profile mdoel stores the user prfile informatioon in the database, one-one relationship with user model.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100, blank=True)
    avatar = models.CharField(max_length=100, choices=AVATAR_CHOICES, default='avatar1.webp')
    location = models.CharField(max_length=100, blank=True) 
    
    #method to get the avatar image url
    def get_avatar_url(self):
        return f'/static/images/avatars/{self.avatar}'
    
    # method ot get the experience of the player
    def get_experience_level(self):
        hands_played_count = HandsPlayed.objects.filter(user=self.user).count()
        if hands_played_count < 100:
            return 'Novice'
        elif hands_played_count < 500:
            return 'Advanced Beginner'
        elif hands_played_count < 1500:
            return 'Intermediate'
        elif hands_played_count < 3000:
            return 'Advanced'
        else:
            return 'Expert'
    def get_experience_percentage(self):
        hands_played_count = HandsPlayed.objects.filter(user=self.user).count()
        max_hands_for_expert = 1000
        return min(hands_played_count / max_hands_for_expert * 100, 100)
    
# The game model tracks the general game information
class Game(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    total_winnings = models.IntegerField(default=0)
    hands_won = models.IntegerField(default=0)
    hands_lost = models.IntegerField(default=0)
    
# The handsplayed model tracks all the hand information which is linked ot a game
class HandsPlayed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='hands_played') 
    hand_id = models.CharField(max_length=255)  
    cards = models.CharField(max_length=255) 
    game_actions = models.ManyToManyField('GameAction', related_name='hands_played')
    ai_cards = models.CharField(max_length=255)  
    community_cards = models.CharField(max_length=1000)  
    won = models.BooleanField(null=True)
    completed = models.BooleanField(default=False)
    small_blind = models.IntegerField(default=0)  
    big_blind = models.IntegerField(default=0)
    is_user_big_blind = models.BooleanField(default=False)

# The game actions model tracks the actions taken within each hand 
class GameAction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='actions')
    action_type = models.CharField(max_length=255)
    amount = models.IntegerField()
    stage = models.CharField(max_length=255)
    is_voluntary = models.BooleanField(default=True)
    ai_action = models.BooleanField(default=False)
    hand = models.ForeignKey(HandsPlayed, on_delete=models.CASCADE, null=True, blank=True)

# The decsion data model tracks the AI's decison data that calcualted by the CFR alogrithm
class DecisionData(models.Model):
    game_action = models.ForeignKey(GameAction, on_delete=models.CASCADE, related_name='decision_data')
    info_set_key = models.TextField()
    strategy = models.JSONField()
    action_taken = models.CharField(max_length=10)
    probabilities = models.JSONField()
    bucket_value = models.IntegerField(null=True, default=None)
    player_hand = models.CharField(max_length=255, null=True) 

# The hand strength model holds all the hand combinations used ot mkae the hand strength grid
class HandStrength(models.Model):
    cards = models.CharField(max_length=255, unique=True)
    bucket_value = models.IntegerField()
    hand_strength = models.IntegerField()
    

short_deck_rl/shortdeck/forms.py
from django import forms
from .models import UserProfile, AVATAR_CHOICES
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

# This class is a form for the UserProfile model 
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nickname', 'avatar' , 'location']
        widgets = {
            'avatar': forms.Select(choices=AVATAR_CHOICES)
        }
        
 # This form is for the User model fields
class UserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

# This ofrm handles the players actions
class PlayerActionForm(forms.Form):
    CHOICES = [
        ('fold', 'Fold'),
        ('call', 'Call'),
        ('raise', 'Raise'),
        ('bet', 'Bet'),
    ]
    action = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
    bet_amount = forms.IntegerField(required=False)
    
# forms class used to chnage the user passowrd in the user model
class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Current Password", widget=forms.PasswordInput)
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Confirm New Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

short_deck_rl/shortdeck/views.py
import os
# Set the Django settings module
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'short_deck_rl.settings')
import django
django.setup()
import pycountry
from . import cards, converting
from .cards import Cards, PokerPlayer, PokerGame
from .forms import UserProfileForm, UserForm
from .forms import PlayerActionForm
from .models import UserProfile, GameAction, HandsPlayed, Game, DecisionData, HandStrength
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from copy import deepcopy
from . import CFR
from . import shared
import uuid
import time
from django.utils import timezone
from django.db.models import Sum
from collections import defaultdict
import logging
import json
from django.http import JsonResponse
import numpy as np
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from collections import Counter
from django.contrib.auth import logout
from django.db.models.functions import TruncWeek, TruncDay
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.forms import PasswordChangeForm
from django.core.serializers.json import DjangoJSONEncoder



#Method to handle the game logic 
def shortdeck(request):
    context = {}
    bigBlind = 10
    limit = 4
    if "newHand" not in request.session or request.session["newHand"]: 
        playerList = cards.PokerPlayer.getPlayerList(2,500)
        # Retrieve the deck from the cards class
        deck = Cards.shortDeck()
        
        # Deal the players cards and the community cards and serialsie / save to the session
        playerCards = cards.dealdeck(2, deck)
        playerList[0].hand = playerCards
        request.session["playerCards"] = converting.serialise_cards(playerCards)
        request.session["deck"] = converting.serialise_cards(deck)

        #Get the curretn game id
        current_game_id = request.session.get("current_game_id")
        current_game = Game.objects.get(id=current_game_id)
        
        # tracks player's current earnings/losses
        if "balance" not in request.session:
            request.session["balance"] = 0
            balance = 0
        else:
            balance = request.session["balance"]
            
        # track player's chips initialised as 1000 at the start of a game
        if "chips" not in request.session:
            request.session["chips"] = 1000
            chips = 1000
        else:
            chips = request.session["chips"]
        
        # The player will go first hwen a new game is started.
        if "buttonPos" not in request.session:
            buttonPos = 0
            request.session["buttonPos"] = 0
        #retrieve button position passed from prior round
        else:
            buttonPos = request.session["buttonPos"]
            
        #sets button player as active and small blind/big blind bets
        activePlayer = buttonPos
        
        # Deduct blinds from balance and chips and mkae the players bet the blinds.
        if activePlayer == 0:
            # Player is on the button, so they post the small blind, the AI posts the big blind
            playerList[(activePlayer + 1) % 2].bet = bigBlind
            playerList[activePlayer].bet = int(bigBlind / 2)
            balance -= int(bigBlind / 2)  
            chips -= int(bigBlind / 2)
            
        else:
            # Player is not on the button, so they post the big blind, the AI is the small blind
            playerList[activePlayer].bet = bigBlind
            playerList[(activePlayer + 1) % 2].bet = int(bigBlind / 2)
            balance -= bigBlind 
            chips -= bigBlind

        #save blanace and chips ot the session
        request.session["balance"] = balance 
        request.session["chips"] = chips 
        
        #stores bets in session and updates player list
        request.session["AIBet"] = playerList[1].bet
        request.session["playerBet"] = playerList[0].bet
        playerBet = playerList[0].bet
        AIBet = playerList[1].bet
        
        # Initialise pot
        pot = 0 
        pot += bigBlind
        pot += int(bigBlind / 2) 
        request.session["pot"] = pot

        # Logging the hands informaiton into the handplayed model
        hand_instance = HandsPlayed.objects.create(
            user=request.user,
            hand_id=generate_hand_id(),
            cards=converting.serialise_cards(playerList[0].hand),
            ai_cards = converting.serialise_cards(playerList[1].hand),
            community_cards = converting.serialise_cards(playerList[0].communityCards),
            game = current_game,
            won=None,
            completed=False,
            small_blind=int(bigBlind / 2),
            big_blind=bigBlind,
            is_user_big_blind=(buttonPos == 1),
        )
        # Store the hand instance ID in the session
        request.session['current_hand_instance_id'] = hand_instance.id  
    
        # Get the game_id and caculate the game stats to beshwon in the poker game
        current_game_id = request.session.get("current_game_id")
        if current_game_id:
            vpip, pfr, af = calculate_game_stats(request.user, current_game_id)
            request.session["vpip"] = vpip
            request.session["pfr"] = pfr
            request.session["af"] = af
        
        # Deal AI's cards
        AI_cards = cards.dealdeck(2, deck)
        playerList[1].hand = AI_cards
        request.session["AI_cards"] = converting.serialise_cards(AI_cards)
        request.session["deck"] = converting.serialise_cards(deck)
            
        # Initialise communityCards as an empty list
        communityCards = [] 
        for p in playerList:
            p.communityCards = deepcopy(communityCards)
        request.session["communityCards"] = converting.serialise_cards(communityCards)
        
        history = []
        request.session["history"] = history

        # Used to keep trakc of how many hands thye've played
        if "hands" not in request.session:
            request.session["hands"] = 0
            hands = 0
        else:
            hands = request.session["hands"]
    
        # action log set to empty
        request.session["actionLog"] = []
        actionLog = []

        request.session["newHand"] = False
    else:
        #retrieves session variables
        deck = converting.deserialise_cards(request.session["deck"])
        playerCards = converting.deserialise_cards(request.session["playerCards"])
        AI_cards = converting.deserialise_cards(request.session["AI_cards"])
        communityCards = converting.deserialise_cards(request.session["communityCards"])
        playerBet = request.session["playerBet"]
        AIBet = request.session["AIBet"]
        buttonPos = request.session["buttonPos"]
        history = request.session["history"]
        activePlayer = request.session["activePlayer"]
        balance = request.session["balance"]
        chips = request.session["chips"]
        hands = request.session["hands"]
        actionLog = request.session["actionLog"]
        pot = request.session["pot"]
        hand_instance_id = request.session['current_hand_instance_id']
        current_game_id = request.session.get("current_game_id")
        newHand = request.session.get("newHand")
        actions = request.session["formChoices"]
        
        #puts variables into playerList
        playerList = cards.PokerPlayer.getPlayerList(2,500)
        playerList[0].bet = playerBet
        playerList[0].hand = playerCards
        
        playerList[1].bet = AIBet
        playerList[1].hand = AI_cards
    
        for p in playerList:
            p.communityCards = deepcopy(communityCards)
            
    # gets the user profile if present 
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None  
        
    # This is where the AI is set, the file is passed into the retrieve_save method
    playerList[1].AI = cards.CFRAgent
    AIinfo, trainingItrs = shared.retrieve_save("training7000")
    playerList[1].info = AIinfo
      
    # not being used anymore, was there when claculted players decison using AI knowledge  
    AIinfo_User, trainingItrs_User = shared.retrieve_save("training3000")
    playerList[0].info = AIinfo_User

    # Gets the users choice
    context = {}
    endRound = False
    if request.method == "POST":
        choice = request.POST.get("choice")
        pot = request.session.get("pot", 0)
        
        if choice and choice != "Next Round":
            history.append(choice)
         
        if len(playerList[0].communityCards) == 0:
            stage = 'Pre-flop'
        elif len(playerList[0].communityCards) == 3:
            stage = 'Flop'
        elif len(playerList[0].communityCards) == 4:
            stage = 'Turn'
        elif len(playerList[0].communityCards) == 5:
            stage = 'River'
        
        request.session['stage'] = stage
        # Get the highest bet by either player
        highest_bet = max(playerList[0].bet, playerList[1].bet)
        # Betting limit set to 4 
        betting_limit = 4
        #retrieve history from session
        history = request.session['history']
  
        # Raise action by the user
        if choice == "Raise":
            # The amount to raise on top of matching the current highest bet
            raise_amount = 20 
            request.session.modified = True 
            # Calculate the amount needed to match the opponent's bet, then add the raise amount
            difference = playerList[1].bet - playerList[0].bet
            playerList[0].bet += difference + raise_amount

short_deck_rl/shortdeck/templates/change_avatar.html
<!--  this is the page which allows the user to chnage their avatar  -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/manageprofile.css' %}">
    <title>Choose Avatar</title>
</head>
<body>
    <div class="avatar-container">
        <h1 class="title">Choose Your Avatar</h1>
        <form method="post" action="{% url 'change_avatar' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!--  current avatar is displayed, defeualt used if no avatar selected yet  -->
            <div class="current-avatar-section">
                <label class="profile-label">Current Avatar:</label>
                <div class="current-avatar-display">
                    {% if userProfile.avatar %}
                        <img src="{{ userProfile.get_avatar_url }}" alt="Player Avatar" class="current-avatar-img">
                    {% else %}
                        <img src="{% static 'images/avatars/default-avatar.webp' %}" alt="Default Avatar" class="current-avatar-img">
                    {% endif %}
                </div>
            </div>
            <!--  This show all the avatars which are available to choose from -->
            <div class="avatar-choices-section">
                {% for value, name in form.fields.avatar.choices %}
                    <label class="avatar-choice" for="avatar{{ forloop.counter }}">
                        <input type="radio" name="avatar" value="{{ value }}" id="avatar{{ forloop.counter }}" {% if userProfile.avatar == value %}checked{% endif %}>
                        <img src="{% static 'images/avatars/' %}{{ value }}" alt="{{ name }}" class="avatar-option-img">
                    </label>
                {% endfor %}
            </div>
            <button type="submit" class="save-changes-btn">Save Changes</button>
        </form>
    </div>
</body>
</html>

short_deck_rl/shortdeck/templates/grid_template.html
<!-- This is the template for the grid that is displayed in the hand review page when revieing an AI decision. The boxews are coloured using the styling based off their bucket and the players hand in highlighted on the grid -->
{% load custom_tags %}
  <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            .hand-strength-grid td {
                border: 1px solid #ccc;
                text-align: center;
                padding: 4px; 
                box-sizing: border-box;
            }
              
            .player-hand {
                background-color: #add8e6; 
            }
            
            .hand-strength-grid td.category-35 {
                background-color: #ff0000; 
            }
              
            .hand-strength-grid td.category-28 {
                background-color: #800080; 
            }
              
            .hand-strength-grid td.category-25 {
                background-color: #ffff00; 
            }
              
            .hand-strength-grid td.category-22 {
                background-color: #008000; 
            }
              
            .hand-strength-grid td.category-17 {
                background-color: #0000ff; 
            }
               
            .hand-strength-grid td.highlight {
                border: 6px solid black;
                top: -3px; 
                right: -3px; 
                bottom: -3px; 
                left: -3px; 
            }  
        </style>
    </head>
    <table class="hand-strength-grid">
        <tr>
            <th></th> 
            {% for rank in ranks %}
            <th>{{ rank }}</th> 
            {% endfor %}
        </tr>
        {% for row in grid_data %}
        <tr>
            <th>{{ row_headers|get_item:forloop.revcounter0 }}</th>
                    
            {% for cell in row %}
            <td class="category-{{ cell.category }}{% if cell.highlight %} highlight{% endif %}">
                {{ cell.bucket_value }}
            </td>
            {% endfor %}

        </tr>
        {% endfor %}
    </table>
    

short_deck_rl/shortdeck/templates/manage_profile.html
<!-- 
    This is the manage profile page, the user has the ability to change their nickname and avatar 
    which are displayed in the game, they will also have to ability to open the chnage password pop up and chnage that. 
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;700;900&display=swap" rel="stylesheet">
    <title>Manage Profile</title>
    <link rel="stylesheet" href="{% static 'css/manageprofile.css' %}">
</head>
<body>

    <div class="container profile-container">
        <h1 class="profile-heading">Manage Profile</h1>
        <div class="experience-bar-container">
            <span class="experience-label">{{ user.userprofile.get_experience_level }}</span>
            <div class="experience-bar">
                <div class="experience-bar-fill" style="width: {{ user.userprofile.get_experience_percentage }}%;"></div>
            </div>
        </div>
        {% csrf_token %}
        <div class="current-avatar-section">
            {% if user.userprofile.avatar %}
            <img src="{{ user.userprofile.get_avatar_url }}" alt="Player Avatar" class="current-avatar-img">
            {% else %}
            <img src="{% static 'images/avatars/default-avatar.webp' %}" alt="Default Avatar" class="current-avatar-img">
            {% endif %}

            <div class="form-actions">
                <a href="{% url 'change_avatar' %}" class="btn btn-primary change-avatar-btn">Change Avatar</a>
            </div>
        </div>

        <!--  Form for displaying all the users info aswell as changing the nickname -->
        <form method="post" action="{% url 'manage_profile' %}" class="profile-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-section">
                <label class="profile-label">Username:</label>
                <p>{{ request.user.username }}</p>
            </div>
            
            <div class="form-section">
                <label for="id_first_name" class="profile-label">First Name:</label>
                {{ request.user.first_name }}
            </div>
            
            <div class="form-section">
                <label for="id_last_name" class="profile-label">Last Name:</label>
                {{ request.user.last_name }}
            </div>
            
            <div class="form-section">
                <label for="id_email" class="profile-label">Email:</label>
                {{ request.user.email }}
            </div>

            
            <div class="form-section">
                <label for="id_location" class="profile-label">Location:</label>
                {{ user.userprofile.location }}
            </div>
            
            <div class="form-section">
                <label for="id_nickname" class="profile-label">Nickname:</label>
                <input type="text" name="nickname" value="{{ profile_form.nickname.value }}" class="form-control">

            </div>
            
            <input type="hidden" name="avatar" value="{{ user.userprofile.avatar }}">
            <button type="submit" class="save-changes-btn">Save Changes</button>

        </form>

        <button id="changePasswordButton" class="btn">Change Password</button>
        <div id="passwordChangeModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>

                <!-- Form for changing the password -->
                <form id="passwordChangeForm" method="post" action="{% url 'change_password' %}">

                    {% csrf_token %}
                    <div class="form-group">
                        <label for="currentPassword">Current Password:</label>
                        <input type="password" id="currentPassword" name="old_password" required class="form-control">
                    </div>

                    <div class="form-group"> 
                        <label for="newPassword">New Password:</label>
                        <input type="password" id="newPassword" name="new_password1" required class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="confirmNewPassword">Confirm New Password:</label>
                        <input type="password" id="confirmNewPassword" name="new_password2" required class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary">Change Password</button>
                </form>
            </div>
        </div>
    </div>
</body>
<script src="{% static 'js/manage_profile.js' %}"></script>
</html>

short_deck_rl/shortdeck/templates/register.html
<!-- 
    The registeration Page, redirects to the home page once successfully registered, where they will be prompted to login
-->

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <!-- 
        the script alerts the user of any warning messages that appear using a pop up 
    -->
    <script>
        window.onload = function() {
            {% if messages %}
                {% for message in messages %}
                    alert("{{ message }}");
                {% endfor %}
            {% endif %}
        }
    </script>
</head>
<body>
    <h1 class="title">ShortDeck AI</h1>
    <div class="center-container"> 
        <!-- 
        Standard form for Registration, submitting directs to homepage
        -->
        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="first_name" required>

            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="last_name" required>

            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required> 

            <label for="location">Location:</label>
            <select id="location" name="location" required>
                {% for country in countries %}
                    <option value="{{ country.code }}">{{ country.name }}</option>
                {% endfor %}
            </select>
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>